from __future__ import annotations

DEFAULT_FALLBACK_SURFACE = "generic"
INVALID_SURFACE_VALUES = frozenset({"auto"})
SURFACE_VALIDATION_ERROR = "surface must be explicit"
TRAVERSAL_MODE_VALUES = frozenset({"scroll", "load_more", "view_all", "paginate"})
CAPTURE_NETWORK_OFF = "off"
CAPTURE_NETWORK_ALL_SMALL_JSON = "all_small_json"
CAPTURE_NETWORK_VALUES = frozenset(
    {CAPTURE_NETWORK_OFF, "matched_only", CAPTURE_NETWORK_ALL_SMALL_JSON}
)
LISTING_SURFACE_IDENTIFIER = "listing"
SURFACE_PAIRS = {
    "ecommerce_listing": "ecommerce_detail",
    "ecommerce_detail": "ecommerce_listing",
    "job_listing": "job_detail",
    "job_detail": "job_listing",
}
ALTERNATE_MIN_RECORDS = 2
ALTERNATE_MAX_RECORDS = 3
ALTERNATE_MISMATCH_WARNING_THRESHOLD = 2
INTERNAL_API_ENDPOINTS_PROFILE_KEY = "internal_api_endpoints"
INTERNAL_API_ENDPOINT_URL_KEY = "url"
INTERNAL_API_ENDPOINT_METHOD_KEY = "method"
INTERNAL_API_ENDPOINT_TYPE_KEY = "endpoint_type"
INTERNAL_API_ENDPOINT_FAMILY_KEY = "endpoint_family"
INTERNAL_API_ENDPOINT_SOURCE_RUN_ID_KEY = "source_run_id"
INTERNAL_API_ENDPOINT_ALLOWED_METHODS = frozenset({"GET"})
INTERNAL_API_REPLAY_BLOCKED_PATH_MARKERS = frozenset(
    {
        "/analytics",
        "/api/event/",
        "/events/",
        "/settings",
        "/tracking",
    }
)

__all__ = [
    "ALTERNATE_MAX_RECORDS",
    "ALTERNATE_MIN_RECORDS",
    "ALTERNATE_MISMATCH_WARNING_THRESHOLD",
    "CAPTURE_NETWORK_ALL_SMALL_JSON",
    "CAPTURE_NETWORK_OFF",
    "CAPTURE_NETWORK_VALUES",
    "DEFAULT_FALLBACK_SURFACE",
    "INVALID_SURFACE_VALUES",
    "INTERNAL_API_ENDPOINT_ALLOWED_METHODS",
    "INTERNAL_API_ENDPOINT_FAMILY_KEY",
    "INTERNAL_API_ENDPOINT_METHOD_KEY",
    "INTERNAL_API_ENDPOINT_SOURCE_RUN_ID_KEY",
    "INTERNAL_API_ENDPOINT_TYPE_KEY",
    "INTERNAL_API_ENDPOINT_URL_KEY",
    "INTERNAL_API_ENDPOINTS_PROFILE_KEY",
    "INTERNAL_API_REPLAY_BLOCKED_PATH_MARKERS",
    "LISTING_SURFACE_IDENTIFIER",
    "SURFACE_PAIRS",
    "SURFACE_VALIDATION_ERROR",
    "TRAVERSAL_MODE_VALUES",
]
