"""Stable vocabulary for the relational extraction-memory store."""

EXTRACTION_MEMORY_STATUS_ACTIVE = "active"
EXTRACTION_MEMORY_STATUS_PROVISIONAL = "provisional"
EXTRACTION_MEMORY_STATUS_RETIRED = "retired"
EXTRACTION_MEMORY_STATUS_SUSPENDED = "suspended"
EXTRACTION_MEMORY_STATUS_TRUSTED = EXTRACTION_MEMORY_STATUS_ACTIVE
EXTRACTION_RECIPE_LAYER_PLATFORM = "platform"
EXTRACTION_RECIPE_LAYER_DOMAIN = "domain"
EXTRACTION_RECIPE_LAYER_TEMPLATE = "template"
EXTRACTION_RECIPE_LAYER_LOCALE = "locale"
EXTRACTION_RECIPE_LAYER_EXCEPTION = "exception"
EXTRACTION_RECIPE_LAYER_ORDER = (
    EXTRACTION_RECIPE_LAYER_PLATFORM,
    EXTRACTION_RECIPE_LAYER_DOMAIN,
    EXTRACTION_RECIPE_LAYER_TEMPLATE,
    EXTRACTION_RECIPE_LAYER_LOCALE,
    EXTRACTION_RECIPE_LAYER_EXCEPTION,
)
EXTRACTION_RECIPE_KIND_SELECTORS = "selectors"
EXTRACTION_RECIPE_KIND_CONTRACTS = "contracts"
EXTRACTION_CONTRACT_SELECTION_ORIGIN_GENERIC = "generic"
EXTRACTION_CONTRACT_RESOLVER_OBSERVED = "observed_published_evidence"
EXTRACTION_CONTRACT_OBSERVATION_SOURCE = "successful_crawl"
EXTRACTION_CONTRACT_CANDIDATE_LIMIT = 8
EXTRACTION_CONTRACT_HISTORY_LIMIT = 20
EXTRACTION_CONTRACT_OBSERVABLE_VERDICTS = ("success", "partial", "review")
EXTRACTION_LABEL_KIND_FIELD_FEEDBACK = "field_feedback"
EXTRACTION_LABEL_KIND_GROUNDED_CORRECTION = "grounded_correction"
EXTRACTION_LABEL_KIND_REVIEW_PROMOTION = "review_promotion"
EXTRACTION_CORRECTION_STATUS_REPLAY_PASSED = "replay_passed"
EXTRACTION_CORRECTION_STATUS_REPLAY_FAILED = "replay_failed"
EXTRACTION_CORRECTION_STATUS_ACTIVATED = "activated"
EXTRACTION_COMPILER_VERSION = "recipe.v1"
EXTRACTION_RELEASE_VERSION = "release.v1"
EXTRACTION_MANIFEST_VERSION = "manifest.v1"
SENTINEL_DETERMINISTIC_CHALLENGER_ENABLED = True
SENTINEL_DEFAULT_SAMPLE_RATE = 0.05
SENTINEL_CRITICAL_DRIFT_CONFIRMATION_THRESHOLD = 2
SENTINEL_OBSERVATION_KIND = "sentinel_challenger"
SENTINEL_SUSPENSION_KIND = "sentinel_suspension"
RECIPE_REPAIR_QUEUE_KIND = "recipe_repair_queue"
RECIPE_REPAIR_QUEUE_VERDICT = "repair_queued"
RECIPE_REPAIR_REVIEW_STATES = ("critical_drift", "suspected_drift", "needs_review")
