from __future__ import annotations

NON_RETRYABLE_HTTP_STATUS_REASON = "non_retryable_http_status"
STATIC_DETAIL_NOT_FOUND_REASON = "static_detail_not_found"
STATIC_DETAIL_SHELL_MISMATCH_REASON = "static_detail_shell_mismatch"
BROWSER_ESCALATION_SKIPPED_INSUFFICIENT_BUDGET = "insufficient_budget"

__all__ = (
    "BROWSER_ESCALATION_SKIPPED_INSUFFICIENT_BUDGET",
    "NON_RETRYABLE_HTTP_STATUS_REASON",
    "STATIC_DETAIL_NOT_FOUND_REASON",
    "STATIC_DETAIL_SHELL_MISMATCH_REASON",
)
