export const POLLING_INTERVALS = {
  ACTIVE_JOB_MS: 2000,
  ACTIVE_JOB_SLOW_MS: 5000,
  ACTIVE_JOB_FAST_WINDOW_MS: 120000,
  RECORDS_MS: 2000,
  LOGS_MS: 2000,
  STUCK_RUN_WARNING_MS: 120000,
} as const;

export const RETRY_LIMITS = {
  TERMINAL_RECORDS_RETRY_LIMIT: 4,
} as const;

export const WEBSOCKET_RECONNECT = {
  MIN_DELAY_MS: 500,
  MAX_DELAY_MS: 10000,
  JITTER_RATIO: 0.25,
} as const;

export const RUN_EVENT_STREAM = {
  FLUSH_INTERVAL_MS: 150,
} as const;

export const UI_DELAYS = {
  DEBOUNCE_MS: 250,
  PHASE_TRANSITION_MS: 1500,
  BANNER_AUTO_HIDE_MS: 5000,
} as const;
